Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whittakerj_CSCI3110_Project_2.DataContexts;
using Whittakerj_CSCI3110_Project_2.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;

namespace Whittakerj_CSCI3110_Project_2.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private IdentityDb _idb = new IdentityDb();

        private MovieDb _db = new MovieDb();

        protected override void Dispose(bool disposing)
        {
            _idb.Dispose();
            _db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index(Tag tag)
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            //Admin can't see this
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Admin");
            }
            //User must create a profile
            if (profile == null)
            {
                return RedirectToAction("Create", "Profile");
            }

            //Passing all movies into the viewbag so we can compare them on the index page.
            ViewBag.Movies = _db.Movies.ToList();
            ViewBag.Username = userName;
            return View(_db.WatchedMovies.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whittakerj_CSCI3110_Project_2.DataContexts;
using Whittakerj_CSCI3110_Project_2.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity;

namespace Whittakerj_CSCI3110_Project_2.Controllers
{
    public class MovieController : Controller
    {

        private IdentityDb _idb = new IdentityDb();

        private MovieDb _db = new MovieDb();

        protected override void Dispose(bool disposing)
        {
            _idb.Dispose();
            _db.Dispose();
            base.Dispose(disposing);
        }

        // GET: Movie
        public ActionResult Index()
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            //If they are an admin, they can't be here.

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Admin");
            }

            //User must create a profile
            if (profile == null)
            {
                return RedirectToAction("Create", "Profile");
            }

            return View(_db.Movies.ToList());
        }

        public ActionResult Details(int id)
        {
            Movie movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        //This will show the pay screen.
        public ActionResult Watch(int id)
        {
            Movie movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        [HttpPost]
        public ActionResult Watch(Movie movie)
        {
            if (ModelState.IsValid)
            {
                string userName = User.Identity.GetUserName();
                var id = movie.Id;
                //Search for the watched movie using the Username and the id of the movie
                WatchedMovie watchedmovie = _db.WatchedMovies.Find(userName, id);
                //If it doesn't exist, create it. It means it's the user's first time watching it.
                if (watchedmovie == null)
                {
                    watchedmovie = new WatchedMovie();
                    watchedmovie.email = userName;
                    watchedmovie.MovieId = id;
                    watchedmovie.TimesViewed = 1;
                    _db.WatchedMovies.Add(watchedmovie);
                    _db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
                //if it does exist, just increment TimesViewed by 1.
                watchedmovie.TimesViewed = watchedmovie.TimesViewed + 1;
                _db.Entry(watchedmovie).State = EntityState.Modified;
                _db.SaveChanges();

                return Redirect(movie.IMDBUrl);
            }
            return View(movie);
        }

        //Rewatch movie. No real validation here, but it wasn't asked for.
        //The code is mostly the same as the previous watch, it just doesn't ask for the user to pay so it doesn't need an Httppost.
        public ActionResult WatchAgain(int id)
        {
            string userName = User.Identity.GetUserName();
            WatchedMovie watchedmovie = _db.WatchedMovies.Find(userName, id);
            Movie movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            watchedmovie.TimesViewed = watchedmovie.TimesViewed + 1;
            _db.Entry(watchedmovie).State = EntityState.Modified;
            _db.SaveChanges();
            return Redirect(movie.IMDBUrl);
        }

        public ActionResult Tags(int id)
        {
            Movie movie = _db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        public ActionResult TagsCreate(int id)
        {
            return View();
        }

        public ActionResult TagsEdit(int id)
        {
            return View();
        }

        public ActionResult TagsDelete(int id)
        {
            return View();
        }
    }
}

Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Views/Home/About.cshtml
@{
    ViewBag.Title = "";
}
<h2>@ViewBag.Title</h2>

<br />
<p>Justin Whittaker 
    <a href="mailto:whittakerj@etsu.edu">whittakerj@etsu.edu</a></p>

Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Views/Home/Index.cshtml
@model IEnumerable<Whittakerj_CSCI3110_Project_2.Models.WatchedMovie>

@{
    ViewBag.Title = "Index";
}

<br />
<br />
<table class="table">
    <tr>
        <th>
            <p>Title</p>
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TimesViewed)
        </th>
        <th></th>
    </tr>

@{
    //Counters for movie count and price
    int count = 0;
    double price = 0.00;
}
@foreach (var item in Model) {
    if (item.email == ViewBag.UserName)
    {
    <tr>
        @foreach (var movie in ViewBag.Movies)
        {
            //Looking for the title of the movie using the viewbag
            if (movie.Id == item.MovieId)
            {
        <td>
            @movie.Title
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.TimesViewed)
        </td>
        <td>
            @Html.ActionLink("Manage Tags", "Tags", "Movie", new { id = movie.Id }, null) |
            @Html.ActionLink("Details", "Details", "Movie", new { id = movie.Id }, null) |
            @Html.ActionLink("Watch Again", "WatchAgain", "Movie", new { id = movie.Id }, null)
            @{
                price = price + movie.Price;
                }
        </td>
                    }
                }
    </tr>
                        count = count + 1;
                    }
                }

</table>

@*// Format the price string*@
@{string formatValue = String.Format("Total Spent: {0:C}", price); }

<p>Watched Movies: @count</p>
<p>@formatValue</p>