Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whittakerj_CSCI3110_Project_2.DataContexts;
using Whittakerj_CSCI3110_Project_2.Models;
using Microsoft.AspNet.Identity;
using System.Data.Entity;

namespace Whittakerj_CSCI3110_Project_2.Controllers
{

    public class ProfileController : Controller
    {

        private IdentityDb _idb = new IdentityDb();

        private MovieDb _db = new MovieDb();

        protected override void Dispose(bool disposing)
        {
            _idb.Dispose();
            _db.Dispose();
            base.Dispose(disposing);
        }

        // GET: profile
        public ActionResult Create()
        {
            //Since we know the user will have an Asp.net Identity, we do not generally need to pass ids and will just get their Username
            //from their identity. This is used throughout this entire controller.
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            if (profile == null)
            {
                ViewBag.userName = userName;
                return View();
            }
            return RedirectToAction("Details");
        }

        [HttpPost]
        public ActionResult Create(Profile profile)
        {
            if (ModelState.IsValid)
            {
                _db.Profiles.Add(profile);
                _db.SaveChanges();
                return RedirectToAction("Details");
            }

            return RedirectToAction("Details");
        }

        public ActionResult Details()
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            if (profile == null)
            {
                return RedirectToAction("Create");
            }
            return View(profile);
        }

        public ActionResult Edit()
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            if (profile == null)
            {
                return HttpNotFound();
            }
            ViewBag.userName = userName;
            return View(profile);
        }

        [HttpPost]
        public ActionResult Edit(Profile profile)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(profile).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(profile);
        }

        public ActionResult Delete()
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete()
        {
            string userName = User.Identity.GetUserName();
            Profile profile = _db.Profiles.Find(userName);
            _db.Profiles.Remove(profile);
            _db.SaveChanges();
            return RedirectToAction("Create");
        }
    }
}

Whittakerj CSCI3110 Project 2/Whittakerj CSCI3110 Project 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>             
                @Html.ActionLink("Fantasmic Online Movie Rental", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("View Profile", "Create", "Profile")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                <img src="~/Content/movie-popcorn-clipart-no-background-popcorn-555px.png"  height="50" width="50"/>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Project 2 </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>